ros_topic_name: "/model/vehicle_blue/cmd_vel"
gz_topic_name: "/model/vehicle_blue/cmd_vel"
ros_type_name: "geometry_msgs/msg/Twist"
gz_type_name: "gz.msgs.Twist"
direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ